name: Test Pull Requests To Master (Node 17.0+)

on:
  push:
    branches:
      - greenkeeper/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm versions
      run: |
        node --version
        npm --version
    - name: ci install
      run: npm ci
    - name: build
      run: npm run build --if-present
      env:
        CI: true
        NODE_OPTIONS: --openssl-legacy-provider # necessary for webpack v4 in node 17+
    - name: module test
      run: npm run test:module
    - name: run all code tests
      run: npm test
    - name: test package import
      run: |
        npm install ts-node @std/esm
        npm run test:import
    - name: test package require
      run: |
        npm run test:require
